name: Lint code base

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          args: "**/*.md"
